### ISSUE TITLE
TradeMe - error report (Mypet)

### ISSUE THREAD

**Issue by momoservertw** [Zrips/TradeMeAddon#11]
Trading get fail after accepted the request.
If I disable MyPet trading feature, it will not get this error.
Please fix it, thanks.

TradeMe version: 6.0.0.3  (latest)
Spigot version: git-Spigot-078a7f5-7fa173e (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)  (latest)
Mypet version: Premium-3.0-SNAPSHOT #650 (latest)

[04:21:58 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'trade' in plugin TradeMe v6.0.0.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702) ~[spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1641) ~[spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at net.minecraft.server.v1_13_R2.PlayerConnection.chat(PlayerConnection.java:1557) ~[spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.chat(CraftPlayer.java:320) ~[spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at me.Zrips.TradeMe.Actions.makeOffer(Actions.java:86) ~[TradeMe6.0.0.3.jar:?]
        at me.Zrips.TradeMe.commands.CommandsHandler.onCommand(CommandsHandler.java:84) ~[TradeMe6.0.0.3.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702) ~[spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1641) ~[spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at net.minecraft.server.v1_13_R2.PlayerConnection.chat(PlayerConnection.java:1557) ~[spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.chat(CraftPlayer.java:320) ~[spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at me.Zrips.TradeMe.PlayerListener.onPlayerInteract(PlayerListener.java:106) ~[TradeMe6.0.0.3.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1814) ~[spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(SourceFile:69) ~[spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(SourceFile:13) ~[spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_181]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NoSuchMethodError: de.Keyle.MyPet.api.entity.MyPet.getSkilltree()Lde/Keyle/MyPet/api/skill/skilltree/SkillTree;
        at me.Zrips.TradeMe.SpecialActionPack.MyPetUtil.Buttons(MyPetUtil.java:164) ~[TradeMe6.0.0.3.jar:?]
        at me.Zrips.TradeMe.Util.updateAmountOffer(Util.java:965) ~[TradeMe6.0.0.3.jar:?]
        at me.Zrips.TradeMe.commands.list.accept.perform(accept.java:76) ~[TradeMe6.0.0.3.jar:?]
        at me.Zrips.TradeMe.commands.CommandsHandler.onCommand(CommandsHandler.java:195) ~[TradeMe6.0.0.3.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        ... 34 more

**Comment by Zrips** [comment]
Should be resolved
