### ISSUE TITLE
InventoryClickEvent Issue

### ISSUE THREAD

**Issue by R1NZLER15** [Zrips/TradeMeAddon#21]
Plugin version: 6.0.3.0
Server version: 1.15.2
Server software: Paper Build #176
<details>
  <summary>Error log (Open)</summary>

```
[13:20:57] [Server thread/ERROR]: Could not pass event InventoryClickEvent to TradeMe v6.0.3.0
java.lang.NullPointerException: null
	at me.Zrips.TradeMe.Util$2.click(Util.java:423) ~[?:?]
	at com.TradeMe.CMIGUI.GUIManager.processClick(GUIManager.java:189) ~[?:?]
	at com.TradeMe.CMIGUI.GUIListener.onInventoryClick(GUIListener.java:135) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1209.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-176]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-176]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-176]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-176]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2333) ~[patched_1.15.2.jar:git-Paper-176]
	at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.15.2.jar:git-Paper-176]
	at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.15.2.jar:git-Paper-176]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-176]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-176]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-176]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-176]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-176]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1058) ~[patched_1.15.2.jar:git-Paper-176]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1051) ~[patched_1.15.2.jar:git-Paper-176]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-176]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1122) ~[patched_1.15.2.jar:git-Paper-176]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:940) ~[patched_1.15.2.jar:git-Paper-176]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```
</details>

**Comment by Zrips** [comment]
Should be resolved
