### ISSUE TITLE
Error in 1.17

### ISSUE THREAD

**Issue by Strahilchu** [Zrips/TradeMeAddon#52]
Paper 1.17 #42
TradeMe 6.0.5.4
CMI 9.0.0.1
CMILib 1.0.2.2

[09:20:29 INFO]: Strahil211 issued server command: /trade
[09:20:29 INFO]: Error {0}
[09:20:29 INFO]: java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.PacketPlayOutChat
[09:20:29 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Class.getMethod(String, java.lang.Class[])" because "com.TradeMe.CMILib.RawMessageManager.nmsChatSerializer" is null
[09:20:29 WARN]:        at com.TradeMe.CMILib.RawMessageManager.send(RawMessageManager.java:64)
[09:20:29 WARN]:        at com.TradeMe.CMILib.RawMessage.show(RawMessage.java:515)
[09:20:29 WARN]:        at com.TradeMe.CMILib.RawMessage.show(RawMessage.java:497)
[09:20:29 WARN]:        at com.TradeMe.CMILib.RawMessage.show(RawMessage.java:544)
[09:20:29 WARN]:        at me.Zrips.TradeMe.TradeMe.ShowPagination(TradeMe.java:802)
[09:20:29 WARN]:        at me.Zrips.TradeMe.commands.CommandsHandler.help(CommandsHandler.java:279)
[09:20:29 WARN]:        at me.Zrips.TradeMe.commands.CommandsHandler.onCommand(CommandsHandler.java:54)
[09:20:29 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[09:20:29 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[09:20:29 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821)
[09:20:29 WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2185)
[09:20:29 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1996)
[09:20:29 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1977)
[09:20:29 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[09:20:29 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[09:20:29 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
[09:20:29 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[09:20:29 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[09:20:29 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[09:20:29 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1340)
[09:20:29 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:193)
[09:20:29 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[09:20:29 WARN]:        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1319)
[09:20:29 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1312)
[09:20:29 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:110)
[09:20:29 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1456)
[09:20:29 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1180)
[09:20:29 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[09:20:29 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[09:20:29 INFO]: Failed to show json message with packets, using command approach

**Comment by Strahilchu** [comment]
Fixed with TradeMe v6.1.0.0

Thank you!
