### ISSUE TITLE
Error appear in the console, the trades dont finish when they accept

### ISSUE THREAD

**Issue by AlfreDGR** [Zrips/TradeMeAddon#64]
[18:55:53 WARN]: [TradeMe] Task #15780 for TradeMe v6.1.0.1 generated an exception
java.lang.NullPointerException: Cannot invoke "de.Keyle.MyPet.api.repository.PlayerManager.getMyPetPlayer(org.bukkit.entity.Player)" because the return value of "de.Keyle.MyPet.MyPetApi.getPlayerManager()" is null
        at me.Zrips.TradeMe.SpecialActionPack.MyPetUtil.isLegit(MyPetUtil.java:244) ~[TradeMe6.1.0.1.jar:?]
        at me.Zrips.TradeMe.Util.checkTradeLegit(Util.java:731) ~[TradeMe6.1.0.1.jar:?]
        at me.Zrips.TradeMe.Counter.counter(Counter.java:70) ~[TradeMe6.1.0.1.jar:?]
        at me.Zrips.TradeMe.Counter$1.run(Counter.java:154) ~[TradeMe6.1.0.1.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-165]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-165]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Paper-165]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-165]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-165]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-165]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-165]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by Zrips** [comment]
Well you are trying to run mypet plugin which is not supported on 1.17 servers. Tho this does expose issue with TradeMe which will get a fix. For time being simply not use MyPet plugin until it gets appropriate update
