### ISSUE TITLE
TradeMe try to execute a task while disabled?

### ISSUE THREAD

**Issue by CodeHorizon118** [Zrips/TradeMeAddon#69]
**CMILib ver:**    

[00:20:33 INFO]: CMILib version 1.1.0.2
[00:20:33 INFO]: CMI library
[00:20:33 INFO]: Website: https://www.spigotmc.org/resources/cmilib.87610/
[00:20:33 INFO]: Author: Zrips

**TradeMe ver:**

[00:20:49 INFO]: TradeMe version 6.1.1.0
[00:20:49 INFO]: Powerfull trade plugin
[00:20:49 INFO]: Website: https://www.spigotmc.org/resources/trademe.7544/
[00:20:49 INFO]: Author: Zrips

**Error .log:**

```
[20:15:15] [Server thread/WARN]: [TradeMe] Task #2696104 for TradeMe v6.1.1.0 generated an exception
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.validate(CraftScheduler.java:537) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:236) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:232) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:177) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:146) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.scheduler.BukkitRunnable.runTaskAsynchronously(BukkitRunnable.java:63) ~[patched_1.16.5.jar:git-Purpur-1171]
	at de.Keyle.MyPet.repository.types.SqLiteRepository.addMyPetPlayer(SqLiteRepository.java:964) ~[?:?]
	at de.Keyle.MyPet.api.repository.PlayerManager.registerMyPetPlayer(PlayerManager.java:98) ~[?:?]
	at me.Zrips.TradeMe.SpecialActionPack.MyPetUtil.isLegit(MyPetUtil.java:247) ~[?:?]
	at me.Zrips.TradeMe.Util.checkTradeLegit(Util.java:729) ~[?:?]
	at me.Zrips.TradeMe.Counter.counter(Counter.java:70) ~[?:?]
	at me.Zrips.TradeMe.Counter$1.run(Counter.java:154) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1503) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:449) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1416) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Full TradeMe ERROR LOG:** https://www.toptal.com/developers/hastebin/wapulejuca.properties

We cant reach any solution, only see that error includes: "`de.Keyle.MyPet.repository.types.SqLiteRepository.addMyPetPlayer(SqLiteRepository.java:964) ~[?:?]`" and "`at de.Keyle.MyPet.api.repository.PlayerManager.registerMyPetPlayer(PlayerManager.java:98) ~[?:?]`"

### **Possible SQL error from MyPet?**

**MyPet ver:**

[00:23:18 INFO]: MyPet version 3.12 (DEV)
[00:23:18 INFO]: Website: https://www.spigotmc.org/resources/mypet.12725/
[00:23:18 INFO]: Author: Keyle

![MyPet](https://user-images.githubusercontent.com/85849908/146280325-9ec1c3b0-ab6e-4efa-9bff-f1a634da2e4a.png)

**Comment by CodeHorizon118** [comment]
**EDIT:**

I see this after 15 min of server restart, test /trade command and was succesful working... I do not know what it could be...

```
[00:27:32 WARN]: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_UNIQUE]  A UNIQUE constraint failed (UNIQUE constraint failed: players.name)
[00:27:32 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1012)
[00:27:32 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1024)
[00:27:32 WARN]:        at org.sqlite.core.DB.execute(DB.java:863)
[00:27:32 WARN]:        at org.sqlite.core.DB.executeUpdate(DB.java:904)
[00:27:32 WARN]:        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:98)
[00:27:32 WARN]:        at de.Keyle.MyPet.repository.types.SqLiteRepository$14.run(SqLiteRepository.java:954)
[00:27:32 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[00:27:32 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
[00:27:32 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[00:27:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[00:27:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[00:27:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by Zrips** [comment]
Looks to be more of an issue with MyPet plugin, TradeMe plugin tries to register new player as pet owner if there isint a record already, when you start trading with pets, but as error indicates mypet plugin is disabled at the moment and from last error it looks that MyPet plugin has issues with SQLite data base connection in general, checking entire startup log or checking for any error logs could help out. 
Did some testing to be sure that MyPet plugin works as intended and it does with latest dev builds.
