### ISSUE TITLE
Could not pass event PlayerQuitEvent 

### ISSUE THREAD

**Issue by LoToRTv** [Zrips/TradeMeAddon#8]
Hello pls help me with error ? 

[13:06:14 ERROR]: Could not pass event PlayerQuitEvent to TradeMe v6.0.0.2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.2.jar:git-Paper-415]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-415]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-415]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-415]
        at net.minecraft.server.v1_13_R2.PlayerList.disconnect(PlayerList.java:429) ~[patched_1.13.2.jar:git-Paper-415]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1440) ~[patched_1.13.2.jar:git-Paper-415]
        at net.minecraft.server.v1_13_R2.NetworkManager.handleDisconnection(NetworkManager.java:349) ~[patched_1.13.2.jar:git-Paper-415]
        at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:154) ~[patched_1.13.2.jar:git-Paper-415]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1118) ~[patched_1.13.2.jar:git-Paper-415]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-415]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-415]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-415]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_181]
        at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[?:1.8.0_181]
        at me.Zrips.TradeMe.PlayerListener.onLogOut(PlayerListener.java:511) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor671.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-415]
        ... 12 more

**Comment by Zrips** [comment]
Should be resolved
